[workspace]
members = ["crates/*"]
exclude = ["test-project",  "crates/salt_ide/src/plugin/tests/unit_tests", "src/tests/mock_project", "crates/salt/example-crate"]
resolver = "2"

[workspace.dependencies]
rustc_plugin = "=0.11.0-nightly-2024-12-01"
rustc_utils = "=0.11.0-nightly-2024-12-01"